package gosyncmodules

const SampleConfig = `### Sample config generated by the program. Edit accordingly ###
[ADServer]
Host = <host ip>
#ADPort = 389 for non ssl and 636 for ssl
Port = 389
UseTLS = false
# set InsecureSkipVerify to true for testing, to accept the certificate without any verification.
InsecureSkipVerify = true
#CRTValidFor will not be honored if InsecureSkipVerify is set to true.
CRTValidFor = example1.domain.com
#Path to the pem file, which is used to create the custom CA pool. Will not be honored if InsecureSkipVerify is set to true.
#CRTPath = /etc/ldap.crt
#Page the result size to prevent possible OOM error and crash
Page = 500
#AD Connection Timeout in seconds (Defaults to 10)
ConnTimeOut = 10
username = cn=neo,cn=Users,dc=example,dc=com
password = somepassword
basedn = ou=someou,dc=example,dc=com
#Attributes required to be pulled
attr = givenName, unixHomeDirectory, sn, loginShell, memberOf, dn, o, uid, objectclass, cn, displayName, cn, uidNumber, gidNumber, member
#ldap filter
filter = (cn=*)

[LDAPServer]
Host = <ldap server ip>
Port = 389
UseTLS = false
InsecureSkipVerify = true
CRTValidFor = ldapserver.example.com
#CRTPath = /etc/ldap/sasl2/server.crt
#Page LDAP result
Page = 500
#LDAP Connection Timeout in seconds (Defaults to 10)
ConnTimeOut = 10
username = cn=admin,dc=ldap,dc=example,dc=com
password = somepassword
basedn = ou=someOu,dc=example,dc=com
attr = givenName, homeDirectory, sn, loginShell, memberOf, dn, o, uid, objectclass, cn, displayName, cn, uidNumber, gidNumber, memberUid
filter = (cn=*)


[Replace]
userObjectClass = posixAccount,top,inetOrgPerson
groupObjectClass = top,posixGroup
[Map]
#ADAttribute = ldapattribute, that is mapping AD attribute to the relevant ldap attribute
unixHomeDirectory = homeDirectory
#specify member mapping if you are selecting member attribute from *attr above
member = memberUid

[Sync]
#Add sleep time after each successful sync, in seconds.
sleepTime = 5
# loglevel can be set to either of
#   ErrorLevel = iota // 0
#   WarnLevel // 1
#   InfoLevel // 2
#   DebugLevel // 3
# Uncomment the below line and set to desired value. Defaults to DebugLevel.
# loglevel = DebugLevel
`
